### PR TITLE
US946056: Append securerandom.strongAlgorithms list with SunPKCS11 provider

### PR DESCRIPTION
**Pull request by raghavendran-gopalakrishnan**
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=946056

### CODE REVIEW

**Comment by raghavendran-gopalakrishnan** [comment]
The $JRE_HOME/conf/security/java.security file is modified as requied.
image

**Comment by raghavendran-gopalakrishnan** [comment]
The dev base image was tested against admin and agent-data-sync with commons-lang3 v3.15.0.

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
The build is failing.

**Comment by raghavendran-gopalakrishnan** [comment]
> The build is failing.

Looks like connection timeout 

> 2024-08-01T14:01:26.355029832Z [INFO] DOCKER> [91mRepository 'Main Repository' is invalid.
2024-08-01T14:01:26.355110588Z [repo-oss|http://download.opensuse.org/distribution/leap/15.6/repo/oss/] Valid metadata not found at specified URL
2024-08-01T14:01:26.355154009Z History:
2024-08-01T14:01:26.355162315Z  - Download (curl) error for 'http://cdn.opensuse.org/distribution/leap/15.6/repo/oss/repodata/72ade5926fe32d0008e6c2b8d931d47abbf209bd488d4156b3756b23734a47b6c63917f1940ee441fb363adb08daa46632d51cedfe9c4bea87a0f3fd9452e9db-primary.xml.gz':
2024-08-01T14:01:26.355173198Z    Error code: Connection failed
2024-08-01T14:01:26.355185289Z    Error message: Failed to connect to web-proxy.us.softwaregrp.net port 8080 after 4011 ms: Couldn't connect to server
2024-08-01T14:01:26.355196793Z 
2024-08-01T14:01:26.355207465Z Please check if the URIs defined for this repository are pointing to a valid repository.

**Comment by raghavendran-gopalakrishnan** [comment]
> The build is failing.

The rebuild has passed.

**Review by dermot-hardy — COMMENTED** [review]
@kusumaghoshdastidar Should this be being set in the `/etc/crypto-policies/back-ends/java.config` file in the base image to avoid being overridden by zypper updates?

@raghavendran-gopalakrishnan If we are asserting the the existing `NativePRNGBlocking:SUN` and `DRBG:SUN` algorithms don't work on FIPS-enabled systems then why are we leaving them on the line?  Are there circumstances in which the new `PKCS11:SunPKCS11-NSS-FIPS` algorithm does not work, when it needs to fall back to the previous algorithms?

**Comment by raghavendran-gopalakrishnan** [comment]
> @raghavendran-gopalakrishnan If we are asserting the the existing `NativePRNGBlocking:SUN` and `DRBG:SUN` algorithms don't work on FIPS-enabled systems then why are we leaving them on the line? Are there circumstances in which the new `PKCS11:SunPKCS11-NSS-FIPS` algorithm does not work, when it needs to fall back to the previous algorithms?

I think its required when running on Jenkins.

**Comment by michael-bryson** [comment]
@raghavendran-gopalakrishnan is this PR still required or can it be closed?

**Pull request closed without merging**
